// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5uVd7LJFwBr861WKce8kOxfacH3DKGM',
    appId: '1:412095728219:web:d768fefc4e083779f90d7e',
    messagingSenderId: '412095728219',
    projectId: 'gogreenplantshop-c0d18',
    authDomain: 'gogreenplantshop-c0d18.firebaseapp.com',
    storageBucket: 'gogreenplantshop-c0d18.appspot.com',
    measurementId: 'G-LQJ7D9GDZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAykmeB-rfdXP2PNj_mYjBp0uCxT5RFDQ',
    appId: '1:412095728219:android:8f4ddf0f55a546c6f90d7e',
    messagingSenderId: '412095728219',
    projectId: 'gogreenplantshop-c0d18',
    storageBucket: 'gogreenplantshop-c0d18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzn_0mpn57IIcD7DfoCODqO_7sx4kcb10',
    appId: '1:412095728219:ios:f35391ab41826d0cf90d7e',
    messagingSenderId: '412095728219',
    projectId: 'gogreenplantshop-c0d18',
    storageBucket: 'gogreenplantshop-c0d18.appspot.com',
    iosClientId: '412095728219-ht1qs14fnv1hvud7dd006ssbbo2coil5.apps.googleusercontent.com',
    iosBundleId: 'com.gogreen.plantshop26',
  );
}
